{
    "targets": [
        {
            "target_name": "ocr",
            "type": "static_library",
            "include_dirs": [
                "<!(node -e \"require('nan')\")",
                "../",
                "../../third-party/leptonica/src",
                "../../third-party/tesseract/api",
                "../../third-party/tesseract/ccmain",
                "../../third-party/tesseract/ccstruct",
                "../../third-party/tesseract/ccutil",
                "../../third-party/tesseract/classify",
                "../../third-party/tesseract/cube",
                "../../third-party/tesseract/cutil",
                "../../third-party/tesseract/dict",
                "../../third-party/tesseract/neural_networks/runtime",
                "../../third-party/tesseract/opencl",
                "../../third-party/tesseract/textord",
                "../../third-party/tesseract/viewer",
                "../../third-party/tesseract/wordrec",
                "../../third-party/opencv/include",
                "../../third-party/opencv/3rdparty/openexr",
                "../../third-party/opencv/3rdparty/openexr/Half/",
                "../../third-party/opencv/3rdparty/openexr/Iex/",
                "../../third-party/opencv/3rdparty/openexr/IlmImf/",
                "../../third-party/opencv/3rdparty/openexr/IlmThread/",
                "../../third-party/opencv/3rdparty/openexr/Imath/",
                "../../third-party/opencv/modules/calib3d/include",
                "../../third-party/opencv/modules/core/include",
                # "../../third-party/opencv/modules/cudaarithm/include",
                # "../../third-party/opencv/modules/cudabgsegm/include",
                # "../../third-party/opencv/modules/cudacodec/include",
                # "../../third-party/opencv/modules/cudafeatures2d/include",
                # "../../third-party/opencv/modules/cudafilters/include",
                # "../../third-party/opencv/modules/cudaimgproc/include",
                # "../../third-party/opencv/modules/cudalegacy/include",
                # "../../third-party/opencv/modules/cudaobjdetect/include",
                # "../../third-party/opencv/modules/cudaoptflow/include",
                # "../../third-party/opencv/modules/cudastereo/include",
                # "../../third-party/opencv/modules/cudawarping/include",
                "../../third-party/opencv/modules/cudev/include",
                "../../third-party/opencv/modules/features2d/include",
                "../../third-party/opencv/modules/flann/include",
                "../../third-party/opencv/modules/hal/include",
                "../../third-party/opencv/modules/highgui/include",
                "../../third-party/opencv/modules/imgcodecs/include",
                "../../third-party/opencv/modules/imgproc/include",
                # "../../third-party/opencv/modules/java/include",
                "../../third-party/opencv/modules/ml/include",
                "../../third-party/opencv/modules/objdetect/include",
                "../../third-party/opencv/modules/photo/include",
                # "../../third-party/opencv/modules/python/include",
                "../../third-party/opencv/modules/shape/include",
                "../../third-party/opencv/modules/stitching/include",
                "../../third-party/opencv/modules/superres/include",
                "../../third-party/opencv/modules/ts/include",
                "../../third-party/opencv/modules/video/include",
                "../../third-party/opencv/modules/videoio/include",
                # "../../third-party/opencv/modules/videostab/include",
                # "../../third-party/opencv/modules/viz/include",
                "../../third-party/opencv/modules/world/include",
                "../../third-party/opencv_contrib/modules/adas/include",
                "../../third-party/opencv_contrib/modules/aruco/include",
                "../../third-party/opencv_contrib/modules/bgsegm/include",
                "../../third-party/opencv_contrib/modules/bioinspired/include",
                "../../third-party/opencv_contrib/modules/ccalib/include",
                "../../third-party/opencv_contrib/modules/contrib_world/include",
                # "../../third-party/opencv_contrib/modules/cvv/include",
                # "../../third-party/opencv_contrib/modules/datasets/include",
                # "../../third-party/opencv_contrib/modules/datasetstools/include",
                "../../third-party/opencv_contrib/modules/dpm/include",
                "../../third-party/opencv_contrib/modules/face/include",
                # "../../third-party/opencv_contrib/modules/line_descriptor/include",
                # "../../third-party/opencv_contrib/modules/matlab/include",
                "../../third-party/opencv_contrib/modules/optflow/include",
                "../../third-party/opencv_contrib/modules/reg/include",
                "../../third-party/opencv_contrib/modules/rgbd/include",
                "../../third-party/opencv_contrib/modules/saliency/include",
                "../../third-party/opencv_contrib/modules/stereo/include",
                "../../third-party/opencv_contrib/modules/structured_light/include",
                "../../third-party/opencv_contrib/modules/surface_matching/include",
                "../../third-party/opencv_contrib/modules/text/include",
                "../../third-party/opencv_contrib/modules/tracking/include",
                "../../third-party/opencv_contrib/modules/xfeatures2d/include",
                "../../third-party/opencv_contrib/modules/ximgproc/include",
                "../../third-party/opencv_contrib/modules/xobjdetect/include",
                "../../third-party/opencv_contrib/modules/xphoto/include"
            ],
            "sources": [
                "./ocr.cpp"
            ]
        }
    ]
}
